---
title: "Lab04_Lambertucci"
author: "Caue Esteves Lambertucci - 296094"
format: pdf
editor: visual
---

Q1.

```{r}
library(readxl)
library(tidyverse)
```

Q2.

```{r}
fname <- "WDIEXCEL.xlsx"
```

Q3.

```{r}
countries <- read_excel(fname, sheet = "Country")
```

Q4.

```{r}
countries <- countries %>%
  filter(`Short Name` %in% c("Brazil", "Argentina", "Chile", 
                             "United States", "Germany"))
```

Q5.

```{r}
WDI <- read_excel(fname, sheet = "Data")
```

Q6.

```{r}
WDI <- WDI %>%
  select(`Country Code`, `Indicator Code`, `1960`:`2018`)

```

Q7.

Não os dados não estão no formato Tidy, cada ano é uma coluna não uma linha

```{r}
WDI <- WDI %>%
  pivot_longer(
    cols = `1960`:`2018`,
    names_to = "YEAR",
    values_to = "value"
  )
```

Q8.

```{r}
class(WDI$YEAR)

WDI <- WDI %>%
  mutate(YEAR = as.integer(YEAR))

class(WDI$YEAR)
```

Q9.

```{r}
WDI_wide <- WDI %>%
  pivot_wider(
    names_from = `Indicator Code`,
    values_from = value
  )

WDI_final <- WDI_wide %>%
  inner_join(countries %>% select(`Country Code`, `Short Name`),
             by = "Country Code") %>%
  select(`Country Code`, `Short Name`, YEAR, SP.DYN.CBRT.IN)
```

Q10.

```{r}
WDI_final <- WDI_final %>%
  arrange(`Country Code`, YEAR)
WDI_final
```

Q11.

```{r}
ggplot(WDI_final, aes(x = YEAR, y = SP.DYN.CBRT.IN, 
                      color = `Short Name`)) +
  geom_line(linewidth = 1) +
  labs(
    title = "Taxa de Natalidade Bruta ao Longo do Tempo",
    x = "Ano",
    y = "Taxa de Natalidade (por 1.000 pessoas)",
    color = "País"
  )
```

Hora e Data

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
