---
title: "lab02"
author: "Caue"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)
#conexão com SQL
con <- dbConnect(SQLite(), "me315.sqlite")
```

```{sql connection=con}
SELECT * FROM PRESERVE
```

1

```{sql connection=con}
SELECT STATE, PNO, PNAME FROM PRESERVE
ORDER BY STATE
```

2\.

```{sql connection=con}
SELECT STATE, PNO, PNAME FROM PRESERVE
ORDER BY STATE DESC
```

3\.

```{sql connection=con}
SELECT STATE, PNO, PNAME FROM PRESERVE
ORDER BY STATE DESC, PNO DESC
```

4\.

```{sql connection=con}
SELECT STATE, PNO, PNAME FROM PRESERVE
WHERE STATE = 'AZ'
ORDER BY PNO DESC
```

5\.

```{sql connection=con}
SELECT PNO, ACRES, PNAME FROM PRESERVE
WHERE STATE = 'AZ'
ORDER BY STATE
```

6\.

```{sql connection=con}
SELECT * FROM PRESERVE
ORDER BY ACRES DESC, PNAME
```

7\.

```{sql connection=con}
SELECT PNO, PNAME FROM PRESERVE
ORDER BY ACRES DESC
```

8\.

```{sql connection=con}
SELECT STATE, FEE, PNAME FROM PRESERVE
ORDER BY STATE, FEE DESC, PNAME DESC
```

9\.

```{sql connection=con}
SELECT PNO, ACRES FROM PRESERVE
ORDER BY PNO
LIMIT 3
```

EXERCICIOS DA LISTA

1\.

```{sql connection=con}
SELECT * FROM PRESERVE
ORDER BY ACRES
```

2\.

```{sql connection=con}
SELECT PNAME, FEE FROM PRESERVE
WHERE STATE = 'MT'
ORDER BY PNAME DESC
```

3\.

```{sql connection=con}
SELECT FEE, ACRES FROM PRESERVE
ORDER BY FEE, ACRES
```

4\.

```{sql connection=con}
SELECT PNAME FROM PRESERVE
WHERE STATE = 'AZ' ORDER BY PNO
```

5\.

```{sql connection=con}
SELECT STATE, FEE, PNO FROM PRESERVE
WHERE ACRES > 100 ORDER BY STATE DESC, FEE DESC, PNO
```

6\.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE >= 'M'
```

7\.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE >= 'M'
```

9\.

```{sql connection=con}
SELECT * FROM EMPLOYEE
ORDER BY ENAME
```

10\.

```{sql connection=con}
SELECT ENAME, SALARY FROM EMPLOYEE
WHERE SALARY > 2000 ORDER BY SALARY DESC
```

11\.

```{sql connection=con}
SELECT DNO, ENO, ENAME FROM EMPLOYEE
ORDER BY DNO DESC, ENO
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
