---
title: "Lista6"
author: "Cauê Esteves Lambertucci - 296094"
format: typst
editor: visual
---

```{r}
library(DBI)
library(RSQLite)
knitr::opts_chunk$set(max.print = Inf)
# Conecta/Cria o arquivo
con <- dbConnect(RSQLite::SQLite(), "purchase.sqlite")
```

1\.

```{sql connection = con}
SELECT PNO, SUM(COST) AS custo_total FROM PURCHASE
GROUP BY PNO
```

2

```{sql connection = con}
SELECT ENO, SUM(COST) AS custo_total FROM PURCHASE
GROUP BY ENO
```

3\.

```{sql connection = con}
SELECT PJNO, ENO, SUM(COST) AS custo_total FROM PURCHASE
GROUP BY PJNO, ENO
ORDER BY PJNO, ENO
```

4\.

```{sql connection = con}
SELECT PNO, SNO, SUM(COST) AS custo_total FROM PURCHASE
GROUP BY PNO, SNO
ORDER BY PJNO, SNO 
```

5\.

```{sql connection = con}
SELECT PJNO, ENO, SNO, SUM(COST) AS custo_total FROM PURCHASE
GROUP BY PJNO, ENO, SNO
ORDER BY PJNO, ENO, SNO
```

6\.

```{sql connection = con}
SELECT PNO, SNO, ENO, SUM(COST) AS soma_total FROM PURCHASE
GROUP BY PNO, SNO, ENO
ORDER BY PNO, SNO, ENO
```

7\.

```{sql connection = con}
SELECT PJNO, ENO, SNO, SUM(COST) AS custo_total FROM PURCHASE
WHERE PJNO != 'PJ2'
GROUP BY PNO, ENO, SNO
ORDER BY PNO, ENO, SNO
```

8\.

```{sql connection = con}
SELECT PNO, SNO, ENO, SUM(COST) AS custo_total FROM PURCHASE
GROUP BY PNO, SNO, ENO
HAVING custo_total >= 2000
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
