---
title: "lista6"
author: "Caue"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)
#conexão com SQL
con <- dbConnect(SQLite(), "me315.sqlite")
```

```{sql connection=con}
SELECT * FROM PRESERVE
```

1\.

```{sql connection=con}
SELECT state, MIN(acres) AS acres FROM preserve
GROUP BY state
```

2\.

```{sql connection=con}
SELECT state, MAX(acres) AS acres
FROM preserve
WHERE acres > 10000
GROUP BY state
```

3\.

```{sql connection=con}
SELECT STATE, MAX(ACRES) AS ACRES FROM PRESERVE
WHERE ACRES > 10000
GROUP BY STATE
ORDER BY ACRES DESC
```

4\.

```{sql connection=con}
SELECT STATE, PNAME, ACRES
FROM PRESERVE p1
WHERE ACRES = (SELECT MAX(p2.ACRES) FROM PRESERVE p2 WHERE p2.STATE = p1.STATE)
AND ACRES < 25000
```

5\.

```{sql connection=con}
SELECT STATE, MIN(ACRES) AS ACRES
FROM PRESERVE
GROUP BY STATE
HAVING MIN(ACRES) < 100
```

6\.

```{sql connection=con}
SELECT STATE, PNAME, ACRES
FROM PRESERVE p1
WHERE ACRES > 1000
AND ACRES = (SELECT MAX(p2.ACRES) FROM PRESERVE p2 WHERE p2.STATE = p1.STATE AND p2.ACRES > 1000)
AND ACRES < 25000
```

7\.

```{sql connection=con}
SELECT STATE, SUM(ACRES) AS TOTAL_ACRES
FROM PRESERVE
GROUP BY STATE
HAVING SUM(ACRES) >= 10000 AND SUM(ACRES) <= 50000
```

8\.

```{sql connection=con}
SELECT STATE, AVG(ACRES) AS MEDIA_ACRES
FROM PRESERVE
GROUP BY STATE
ORDER BY MEDIA_ACRES DESC
LIMIT 1
```

9\.

```{sql connection=con}
SELECT DNO, AVG(SALARY) AS SALARIO_MEDIO
FROM EMPLOYEE
GROUP BY DNO
```

10\.

```{sql connection=con}
SELECT DNO, SUM(SALARY) AS SOMA_SALARIOS, MAX(SALARY) AS MAIOR_SALARIO, MIN(SALARY) AS MENOR_SALARIO
FROM EMPLOYEE
GROUP BY DNO
```

11\.

```{sql connection=con}
SELECT DNO, COUNT(*) AS QUANTIDADE_FUNCIONARIOS
FROM EMPLOYEE
WHERE DNO <> 40
GROUP BY DNO
```

12\.

```{sql connection=con}
SELECT DNO, COUNT(*) AS QUANTIDADE_FUNCIONARIOS
FROM EMPLOYEE
GROUP BY DNO
HAVING COUNT(*) > 2
```

13\.

```{sql connection=con}
SELECT STATE, SUM(ACRES) AS "sum(acres)"
FROM PRESERVE
WHERE STATE IN ('AZ', 'MA', 'MT')
GROUP BY STATE

UNION ALL

SELECT 'Total', SUM(ACRES)
FROM PRESERVE
WHERE STATE IN ('AZ', 'MA', 'MT')
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
